version: '3.8'

services:
  saltoestudia:
    build:
      context: .
      dockerfile: dockerfile.production
    container_name: saltoestudia-dev-app
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    networks:
      - traefik-net
    labels:
      - 'traefik.enable=true'
      
      # Frontend service (puerto 3000) - TODAS las páginas HTML
      - 'traefik.http.routers.saltoestudia-dev-frontend.rule=Host(`desarrollo.saltoestudia.infra.com.uy`) && !PathPrefix(`/_event`)'
      - 'traefik.http.routers.saltoestudia-dev-frontend.entrypoints=websecure'
      - 'traefik.http.routers.saltoestudia-dev-frontend.service=saltoestudia-dev-frontend'
      - 'traefik.http.routers.saltoestudia-dev-frontend.tls.certresolver=letsencrypt'
      - 'traefik.http.services.saltoestudia-dev-frontend.loadbalancer.server.port=3000'
      
      # Backend service (puerto 8000) - Solo WebSocket y APIs
      - 'traefik.http.routers.saltoestudia-dev-backend.rule=Host(`desarrollo.saltoestudia.infra.com.uy`) && PathPrefix(`/_event`)'
      - 'traefik.http.routers.saltoestudia-dev-backend.entrypoints=websecure'
      - 'traefik.http.routers.saltoestudia-dev-backend.service=saltoestudia-dev-backend'
      - 'traefik.http.routers.saltoestudia-dev-backend.tls.certresolver=letsencrypt'
      - 'traefik.http.services.saltoestudia-dev-backend.loadbalancer.server.port=8000'
      
      - 'traefik.docker.network=traefik-net'

networks:
  traefik-net:
    external: true 