version: "3.8"

services:
  saltoestudia:
    build: .
    container_name: saltoestudia-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=sqlite:///data/saltoestudia.db
      - REFLEX_DB_URL=sqlite:///data/reflex.db
      - REFLEX_ENV=production
    volumes:
      - ./data:/app/data:rw
      - ./logs:/app/logs:rw
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.saltoestudia.rule=Host(`saltoestudia.infra.com.uy`)"
      - "traefik.http.routers.saltoestudia.entrypoints=websecure"
      - "traefik.http.routers.saltoestudia.tls.certresolver=letsencrypt"
      - "traefik.http.services.saltoestudia.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-net"
      # Middleware opcional para seguridad adicional
      - "traefik.http.middlewares.saltoestudia-headers.headers.frameDeny=true"
      - "traefik.http.middlewares.saltoestudia-headers.headers.contentTypeNosniff=true"
      - "traefik.http.routers.saltoestudia.middlewares=saltoestudia-headers"

networks:
  traefik-net:
    external: true 