"""empty message

Revision ID: 20e1d6c0be67
Revises: 
Create Date: 2025-06-24 02:13:56.115776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '20e1d6c0be67'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instituciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('web', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('logo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nivel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duracion_numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duracion_unidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requisitos_ingreso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('informacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_correo'), ['correo'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_correo'))

    op.drop_table('usuarios')
    op.drop_table('cursos')
    op.drop_table('instituciones')
    # ### end Alembic commands ###
