"""empty message

Revision ID: b9ff636d97ad
Revises: f220f758945e
Create Date: 2025-07-14 02:28:07.888937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b9ff636d97ad'
down_revision: Union[str, Sequence[str], None] = 'f220f758945e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sedes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('web', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instituciones', schema=None) as batch_op:
        batch_op.drop_column('direccion')
        batch_op.drop_column('telefono')
        batch_op.drop_column('web')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instituciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('web', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('telefono', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('direccion', sa.VARCHAR(), nullable=True))

    op.drop_table('sedes')
    # ### end Alembic commands ###
