"""empty message

Revision ID: cd9b0956481c
Revises: 20e1d6c0be67
Create Date: 2025-07-13 20:32:04.821071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'cd9b0956481c'
down_revision: Union[str, Sequence[str], None] = '20e1d6c0be67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lugar', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    
    # Actualizar registros existentes con valor por defecto
    op.execute("UPDATE cursos SET lugar = 'Salto' WHERE lugar IS NULL")
    
    # Hacer la columna NOT NULL después de actualizar los datos
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.alter_column('lugar', nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cursos', schema=None) as batch_op:
        batch_op.drop_column('lugar')

    # ### end Alembic commands ###
