"""empty message

Revision ID: f220f758945e
Revises: cd9b0956481c
Create Date: 2025-07-13 22:06:32.420004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f220f758945e'
down_revision: Union[str, Sequence[str], None] = 'cd9b0956481c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ciudad',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('curso',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nivel', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duracion_numero', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('duracion_unidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requisitos_ingreso', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('informacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('institucion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curso_ciudad',
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('ciudad_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudad.id'], ),
    sa.ForeignKeyConstraint(['curso_id'], ['curso.id'], ),
    sa.PrimaryKeyConstraint('curso_id', 'ciudad_id')
    )
    op.drop_table('cursos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(), nullable=False),
    sa.Column('nivel', sa.VARCHAR(), nullable=False),
    sa.Column('duracion_numero', sa.VARCHAR(), nullable=False),
    sa.Column('duracion_unidad', sa.VARCHAR(), nullable=False),
    sa.Column('requisitos_ingreso', sa.VARCHAR(), nullable=False),
    sa.Column('informacion', sa.VARCHAR(), nullable=True),
    sa.Column('institucion_id', sa.INTEGER(), nullable=False),
    sa.Column('lugar', sa.VARCHAR(), nullable=False),
    sa.ForeignKeyConstraint(['institucion_id'], ['instituciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('curso_ciudad')
    op.drop_table('curso')
    op.drop_table('ciudad')
    # ### end Alembic commands ###
