name: 🚀 Deploy Desarrollo to VPS

on:
  push:
    branches:
      - desarrollo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar VPS a known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan 150.230.30.198 >> ~/.ssh/known_hosts

      - name: Debug - Mostrar llaves cargadas en el agente
        run: ssh-add -l

      - name: Debug - Mostrar known_hosts
        run: cat ~/.ssh/known_hosts

      - name: Copiar archivos al VPS (rsync)
        run: |
          rsync -avz --delete --exclude='.git*' --exclude='data/' --exclude='logs/' ./ ubuntu@150.230.30.198:/srv/docker/saltoestudia-desarrollo/

      - name: Ejecutar deploy en el VPS
        run: |
          ssh ubuntu@150.230.30.198 '
            cd /srv/docker/saltoestudia-desarrollo && \
            docker compose down || true && \
            docker compose up -d --build
          '

      - name: Notificar éxito
        run: echo "🚀 Deploy de desarrollo completado con éxito en VPS" 