name: 🚀 Deploy Desarrollo to VPS

on:
  push:
    branches:
      - desarrollo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Agregar VPS a known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.VPS_HOST_IP }} >> ~/.ssh/known_hosts

      - name: Debug - Mostrar llaves cargadas en el agente
        run: ssh-add -l

      - name: Debug - Mostrar known_hosts
        run: cat ~/.ssh/known_hosts

      - name: Copiar configuración de desarrollo
        run: |
          cp docker-compose.desarrollo.yml docker-compose.yml
          cp config-desarrollo.env .env

      - name: Copiar archivos al VPS (rsync)
        run: |
          rsync -avz --delete --exclude='.git*' --exclude='data/' --exclude='logs/' --exclude='.env' ./ ${{ secrets.VPS_HOST }}:/srv/docker/saltoestudia-desarrollo/

      - name: Ejecutar deploy en el VPS
        run: |
          ssh ${{ secrets.VPS_HOST }} '
            cd /srv/docker/saltoestudia-desarrollo && \
            docker compose down --remove-orphans || true && \
            docker rm -f saltoestudia-dev-app || true && \
            docker compose up -d --build
          '

      - name: Notificar éxito
        run: echo "🚀 Deploy de desarrollo completado con éxito en VPS" 